
package introsde.assignment3.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://ws.soap.assignment3.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonListResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonListRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param idPerson
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @param person
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "updatedPerson", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/updatePersonRequest", output = "http://ws.soap.assignment3.introsde/People/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "createdPerson", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.CreatePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/createPersonRequest", output = "http://ws.soap.assignment3.introsde/People/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param id
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idPerson", targetNamespace = "")
    @RequestWrapper(localName = "deletePersonById", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.DeletePersonById")
    @ResponseWrapper(localName = "deletePersonByIdResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.DeletePersonByIdResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/deletePersonByIdRequest", output = "http://ws.soap.assignment3.introsde/People/deletePersonByIdResponse")
    public int deletePersonById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param idPerson
     * @param type
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "personPreferences", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferencesByType", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferencesByType")
    @ResponseWrapper(localName = "readPersonPreferencesByTypeResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferencesByTypeResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonPreferencesByTypeRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonPreferencesByTypeResponse")
    public List<Activity> readPersonPreferencesByType(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "allPreferences", targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/readPreferencesResponse")
    public List<Activity> readPreferences();

    /**
     * 
     * @param idPerson
     * @param idActivity
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "personPreferences", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferencesById", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferencesById")
    @ResponseWrapper(localName = "readPersonPreferencesByIdResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferencesByIdResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonPreferencesByIdRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonPreferencesByIdResponse")
    public Activity readPersonPreferencesById(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "idActivity", targetNamespace = "")
        int idActivity);

    /**
     * 
     * @param idPerson
     * @param activity
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.SavePersonPreferences")
    @ResponseWrapper(localName = "savePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.SavePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/savePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/savePersonPreferencesResponse")
    public void savePersonPreferences(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

    /**
     * 
     * @param idPerson
     * @param activity
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "personPreferences", targetNamespace = "")
    @RequestWrapper(localName = "updatePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonPreferences")
    @ResponseWrapper(localName = "updatePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/updatePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/updatePersonPreferencesResponse")
    public Activity updatePersonPreferences(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

}
